### ISSUE TITLE
Trennseiten

### ISSUE THREAD

**Issue by GUNT0815** [Marty/paperless-scripts#2]
Hallo Marty,

habe gerade auch Dein korrespondierendes Video auf youtube gesehen. IMHO geht das mit dem scannen von mehreren (zweiseitigen) Dokumenten in einem Rutch noch viel einfacher. Paperless-NGX kennt ja "Trennseiten" diese einfach ausdrucken und immer zwischen zwei Dokumente legen. Paperless-NGX teilt dann selbständig die Dokumente auf. 

Siehe auch hier: https://www.synology-forum.de/threads/vielseitiges-pdf-ueber-trennblaetter-auftrennen.124586/page-2#post-1045823

Gruß

**Comment by Marty** [comment]
Moin @GUNT0815, jo das stimmt. Für mich war das Skript aber einfacher, als dutzende Trennseiten einzusortieren. So kann ich einfach einen ganzen Stapel durchheizen. Besonders wenn eine große Sammlung an Dokumenten digitalisiert wird, ist das meiner Meinung nach eine große Zeitersparnis. Viele Grüße
